vich_uploader:
    db_driver: orm
    storage: flysystem
    
    metadata: 
        type: attribute
    mappings:
        annonces_images:
            uri_prefix: /uploads/annonces
            upload_destination: default.storage
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
